const EXPECTED_NETWORK="eip155:84532";
const EXPECTED_CHAIN_ID="0x14a34";
const EXPECTED_ASSET="0x036CbD53842c5426634e7929541eC2318f3dCF7e".toLowerCase();
const EXPECTED_PAY_TO="0x5A2324aA18613FAD4e44bDf0d6c73Ec1f6D87ff8".toLowerCase();
const EXPECTED_AMOUNT="10000";
const DEFAULT_CONTRACT="0xdAC17F958D2ee523a2206206994597C13D831ec7";
const state={startedAt:new Date().toISOString(),checks:{}};
const $=id=>document.getElementById(id);
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem("veridex-ops-report",JSON.stringify(state));$("reportOutput").textContent=JSON.stringify(state,null,2)}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem("veridex-ops-report")||"{}"))}catch{}$("reportOutput").textContent=JSON.stringify(state,null,2)}
function check(i,ok,detail){const el=document.querySelectorAll("#releaseList .check")[i];if(!el)return;const icon=el.querySelector(".icon");icon.textContent=ok?"✓":"×";icon.style.color=ok?"var(--good)":"var(--bad)";state.checks[i]={ok,detail,at:new Date().toISOString()}}
function metric(id,label,ok){const e=$(id);if(!e)return;e.innerHTML=`<i class="dot ${ok===true?"ok":ok===false?"bad":""}"></i>${label}`}
function addr(v){return /^0x[a-fA-F0-9]{40}$/.test(String(v||""))}
function norm(v){return String(v||"").toLowerCase()}
function parseHeader(v){if(!v)return null;for(const text of [v,(()=>{try{return atob(v)}catch{return ""}})()]){try{return JSON.parse(text)}catch{}}return null}
function accepts(c){return Array.isArray(c?.accepts)?c.accepts:Array.isArray(c?.paymentRequirements?.accepts)?c.paymentRequirements.accepts:Array.isArray(c?.requirements)?c.requirements:[]}
async function challenge(){const contract=$("contract").value.trim();if(!addr(contract))throw new Error("Invalid Ethereum contract address.");const t=performance.now();const r=await fetch("/api/diagnostics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chain:"1",contractAddress:contract}),cache:"no-store"});const ms=Math.round(performance.now()-t);const body=await r.json().catch(()=>({}));const c=body.paymentRequired;const a=accepts(c);const o=a.find(x=>norm(x.network)===EXPECTED_NETWORK);const network=!!o,asset=norm(o?.asset)===EXPECTED_ASSET,amount=String(o?.amount??"")===EXPECTED_AMOUNT,payTo=norm(o?.payTo)===EXPECTED_PAY_TO,parsed=a.length>0,healthy=r.status===402,safe=healthy&&parsed&&network&&asset&&amount&&payTo;state.challenge={status:r.status,latencyMs:ms,contractAddress:contract,paymentRequired:c,headers:body.headers||{},guards:{network,asset,amount,payTo},safe,at:new Date().toISOString()};metric("mProxy",r.status===402?"402 OK":`HTTP ${r.status}`,r.status===402);metric("mX402",safe?"GUARDED":"MISMATCH",safe);check(1,true,`diagnostic HTTP ${r.status}`);check(2,healthy,`expected 402, got ${r.status}`);check(3,parsed,`${a.length} option(s) parsed`);check(4,network,"network guard");check(5,asset,"asset guard");check(6,amount,"amount guard");check(7,payTo,"payTo guard");check(11,true,"diagnostics strips payment/signature/authorization headers");$("challengeOutput").textContent=JSON.stringify({verdict:safe?"SAFE CHALLENGE VERIFIED":"CHALLENGE MISMATCH",status:r.status,latencyMs:ms,paymentRequired:c,guards:{network,asset,amount,payTo},paymentSent:false},null,2);save();return safe}
async function concurrency(){const contract=$("contract").value.trim()||DEFAULT_CONTRACT;const t=performance.now();const rs=await Promise.all([1,2,3].map(()=>fetch("/api/diagnostics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chain:"1",contractAddress:contract}),cache:"no-store"})));const out=await Promise.all(rs.map(async r=>({status:r.status,ok:r.status===402,body:await r.json().catch(()=>({}))})));const pass=out.every(x=>x.ok);state.concurrency={pass,durationMs:Math.round(performance.now()-t),results:out.map(x=>({status:x.status,ok:x.ok,requestId:x.body?.headers?.["x-request-id"]||null})),at:new Date().toISOString()};$("concurrencyOutput").textContent=JSON.stringify({verdict:pass?"PASS · 3/3 challenged":"FAIL · unexpected response",paymentSent:false,...state.concurrency},null,2);check(9,true,"product paid button has an in-flight lock");save();return pass}
async function rpc(method,params){const r=await fetch("https://sepolia.base.org",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:Date.now(),method,params})});if(!r.ok)throw new Error(`Base RPC HTTP ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error.message||"RPC error");return j.result}
function usdc(hex){const n=BigInt(hex||"0x0"),w=n/1000000n,f=(n%1000000n).toString().padStart(6,"0").replace(/0+$/,'');return f?`${w}.${f}`:w.toString()}
async function wallet(){if(!window.ethereum){metric("mWallet","NO PROVIDER",false);$("walletKv").innerHTML="<b>provider</b><span>window.ethereum unavailable</span><b>address</b><span>—</span><b>chain</b><span>—</span><b>USDC balance</b><span>—</span>";return}const accounts=await window.ethereum.request({method:"eth_accounts"});const chainId=await window.ethereum.request({method:"eth_chainId"});const address=accounts?.[0]||null;let balance=null,error=null;if(address){try{const data="0x70a08231"+address.slice(2).padStart(64,"0");balance=usdc(await rpc("eth_call",[{to:EXPECTED_ASSET,data},"latest"]))}catch(e){error=e.message}}const ok=chainId===EXPECTED_CHAIN_ID;state.wallet={address,chainId,networkOk:ok,usdcBalance:balance,rpcError:error,at:new Date().toISOString()};metric("mWallet",address?(ok?"CONNECTED":"WRONG CHAIN"):"NOT CONNECTED",address&&ok?true:address?false:null);$("walletKv").innerHTML=`<b>provider</b><span>injected EVM provider</span><b>address</b><span class="mono">${address||"not connected"}</span><b>chain</b><span>${chainId}${ok?" · Base Sepolia":" · expected 0x14a34"}</span><b>USDC balance</b><span>${balance===null?"not read":balance+" USDC"}</span>`;$("walletOutput").textContent=JSON.stringify({address,chainId,networkOk:ok,usdcBalance:balance,rpcError:error,paymentInitiated:false},null,2);save()}
async function production(){const t=performance.now(),r=await fetch(location.href,{cache:"no-store"}),ms=Math.round(performance.now()-t);state.production={ok:r.ok,status:r.status,latencyMs:ms,at:new Date().toISOString()};check(0,r.ok,`console HTTP ${r.status} in ${ms}ms`);save()}
async function all(){const b=$("runAll");b.disabled=true;b.textContent="Running safe checks…";try{await production();await challenge();await concurrency();await wallet();check(10,null,"manual paid-flow error matrix");check(12,null,"manual visual/accessibility review");check(13,true,"JSON report export is available");save()}catch(e){state.lastError={message:e.message,at:new Date().toISOString()};save();console.error(e)}finally{b.disabled=false;b.textContent="Run all safe checks"}}
function exportReport(){save();const u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=u;a.download=`veridex-ops-report-${new Date().toISOString().replace(/[:.]/g,"-")}.json`;a.click();URL.revokeObjectURL(u)}
async function copy(){save();await navigator.clipboard.writeText(JSON.stringify(state,null,2));$("copyBtn").textContent="Copied";setTimeout(()=>$("copyBtn").textContent="Copy report JSON",1200)}
$("contract").value=DEFAULT_CONTRACT;
$("challengeBtn").onclick=async()=>{const b=$("challengeBtn");b.disabled=true;try{await challenge()}catch(e){$("challengeOutput").textContent=JSON.stringify({error:e.message},null,2);state.lastError={message:e.message,at:new Date().toISOString()};save()}finally{b.disabled=false}};
$("concurrencyBtn").onclick=async()=>{const b=$("concurrencyBtn");b.disabled=true;try{await concurrency()}catch(e){$("concurrencyOutput").textContent=JSON.stringify({error:e.message},null,2)}finally{b.disabled=false}};
$("walletBtn").onclick=async()=>{if(!window.ethereum)return wallet();await window.ethereum.request({method:"eth_requestAccounts"});await wallet()};
$("walletReadBtn").onclick=wallet;$("runAll").onclick=all;$("exportBtn").onclick=exportReport;$("copyBtn").onclick=copy;$("clearBtn").onclick=()=>{localStorage.removeItem("veridex-ops-report");location.reload()};window.ethereum?.on?.("accountsChanged",wallet);window.ethereum?.on?.("chainChanged",wallet);load();
