const EXPECTED_NETWORK="eip155:84532";
const EXPECTED_ASSET="0x036CbD53842c5426634e7929541eC2318f3dCF7e".toLowerCase();
const EXPECTED_PAY_TO="0x5A2324aA18613FAD4e44bDf0d6c73Ec1f6D87ff8".toLowerCase();
const EXPECTED_AMOUNT="10000";
const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[m]))}
function short(v){const s=String(v||"");return s.length>24?`${s.slice(0,12)}…${s.slice(-12)}`:s}
function safe(v){try{return JSON.stringify(v,null,2)}catch{return String(v)}}
function toast(message,error=false){const t=$("toast");t.textContent=message;t.className=error?"toast error":"toast";clearTimeout(t._timer);t._timer=setTimeout(()=>t.className="toast hidden",3200)}
function renderRows(items){return items.length?items.map(i=>`<tr><td>${esc(i.userTime||i.timestamp||"—")}</td><td class="mono">${esc(short(i.transactionHash||i.hash))}</td><td>${esc(i.amountUsdc??0)} USDC</td><td><span class="pill ${i.matchedVeridexPayment?"good":"warn"}">${i.matchedVeridexPayment?"VERIFIED":"CHECK"}</span></td><td><a target="_blank" rel="noopener" href="${esc(i.explorerUrl||`https://base-sepolia.blockscout.com/tx/${i.transactionHash||i.hash}`)}">Open ↗</a></td></tr>`).join(""): `<tr><td colspan="5" class="empty">No evidence returned.</td></tr>`}
async function recover(){const b=$("recover");b.disabled=true;b.textContent="Recovering…";try{const accounts=window.ethereum?await window.ethereum.request({method:"eth_accounts"}):[];const chainId=window.ethereum?await window.ethereum.request({method:"eth_chainId"}):null;const address=accounts?.[0]||null;const walletQuery=address&&chainId==="0x14a34"?`?address=${encodeURIComponent(address)}`:"";const r=await fetch(`/api/history${walletQuery}`,{cache:"no-store"});const data=await r.json().catch(()=>({error:"invalid_json"}));if(!r.ok)throw new Error(data.detail||data.error||`History HTTP ${r.status}`);const historical=data.historicalEvidence||[];const wallet=data.walletMatches||[];const all=[...historical,...wallet.filter(x=>!historical.some(h=>h.transactionHash===x.transactionHash))];const verified=all.filter(x=>x.matchedVeridexPayment);$("status").textContent=`${verified.length} verified payment(s) · ${historical.length} supplied hash(es) checked`;$("status").className=verified.length?"status good":"status warn";$("rows").innerHTML=renderRows(all);$("output").textContent=safe({wallet:address,chainId,expected:data.expected,historicalEvidence:historical,walletMatches:wallet});if(address&&chainId!=="0x14a34")toast("Wallet is not on Base Sepolia. Historical hashes were checked anyway.",true);else toast(`${verified.length} payment(s) reconciled on-chain`)}catch(e){$("output").textContent=safe({error:e.message});$("status").textContent="Recovery failed";$("status").className="status error";toast(e.message,true)}finally{b.disabled=false;b.textContent="Recover payments"}}
async function lookup(){const value=$("hash").value.trim();if(!/^0x[a-fA-F0-9]{64}$/.test(value)){toast("Enter a valid 0x transaction hash",true);return}const b=$("lookup");b.disabled=true;b.textContent="Looking up…";try{const r=await fetch(`/api/tx?hash=${encodeURIComponent(value)}`,{cache:"no-store"});const data=await r.json().catch(()=>({}));$("lookupOutput").textContent=safe(data);if(!r.ok)throw new Error(data.error||`Lookup HTTP ${r.status}`);const match=(data.tokenTransfers||[]).some(x=>String(x.tokenAddress||"").toLowerCase()===EXPECTED_ASSET&&String(x.to||"").toLowerCase()===EXPECTED_PAY_TO&&String(x.amount||"")===EXPECTED_AMOUNT);toast(match?"Transaction matches the Veridex payment contract":"Transaction found, but it does not match the configured payment contract",!match)}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent="Lookup transaction"}}
$("recover").onclick=recover;$("lookup").onclick=lookup;$("back").onclick=()=>location.href="/ops";
$("hash").addEventListener("keydown",e=>{if(e.key==="Enter")lookup()});
if(new URLSearchParams(location.search).get("focus")==="lookup")setTimeout(()=>{$("hash")?.focus();$("lookupCard")?.scrollIntoView({behavior:"smooth"})},150);
recover();
